### ISSUE TITLE
Updating app store version is not instantaneous

### ISSUE THREAD

**Issue by kitallis** [tramlinehq/store-quirks#2]
In our tests, it's notable that cancelling an app store submission through the API (or developer rejecting it) can actually take a few seconds to register on the apple side. It may not be internally transactional, hence requires waiting to see that update.

**Comment by nid90** [comment]
When using the App Store Connect API, if you cancel an existing submission and try and update the details of the now editable app store version right away, it fails. This is because the cancel submission API responds without persisting the change and requires a little sleep before you can try and update the details of the newly editable app store version.
